#!/bin/bash
ROOT_DIR=~/rss

TAG="$1"
[ -z "$TAG" ] && echo "Tag must be specified!" && exit
shift;
[ -z "$1" ] && echo "No filenames provided!" && exit
DIR=$(echo $TAG | sed 's/good/other/' | sed 's/bad/unwanted/')

#if [ "x$TAG" == "xgood" ]; then
	wwts -t -T "$TAG" -- "$@" && mkdir -p "$ROOT_DIR/$DIR" && mv -- "$@" "$ROOT_DIR/$DIR"
#elif [ "x$TAG" == "xbad" ]; then
	#wwts -F "$@" -u -T "good" && mkdir -p "$ROOT_DIR/$TAG" && mv -- "$@" "$ROOT_DIR/$TAG"
#else
	#echo "Unknown tag ${TAG}. Must be 'good' or 'bad'."
#fi
