#!/bin/bash
ROOT_DIR=~/rss
GOOD_DIR="$ROOT_DIR/other"
BAD_DIR="$ROOT_DIR/unwanted"

ATO_DIR="$ROOT_DIR/ato"
COFFEE_DIR="$ROOT_DIR/coffee"
COMIC_DIR="$ROOT_DIR/comic"
TOREAD_DIR="$ROOT_DIR/news"
COMPULENTA_DIR="$ROOT_DIR/science"

while [ -d "$ROOT_DIR/.rss" ]; do
	sleep 1
done

shopt -s dotglob

pushd "$ROOT_DIR"
mkdir .rss
wwts_guess * | while read LINE; do
	TAGS=$(echo "$LINE" | grep -o '^\[[^]]*\]')
	FILENAME=$(echo "$LINE" | sed 's/^\[[^]]*\] //')
	GOOD=$(echo "$TAGS" | python3 -c 'from collections import defaultdict;d=defaultdict(float, eval(input()));print(d["good"]>d["bad"]);')
	if [ "$GOOD" == "True" ]; then
		mkdir -p "$GOOD_DIR"
		mv -vb -S .html -- "$FILENAME" "$GOOD_DIR"
	else
		mkdir -p "$BAD_DIR"
		mv -vb -S .html -- "$FILENAME" "$BAD_DIR"
	fi
done
rmdir .rss
popd

# Sort by type.
COMIC_FILTER='explosm\|developerslife\|dilbert\|defun[.]co\|devopsreactions\|apijoy\|netlore\|lol-wall\|simpledesktops\|velik-moguch\|StupidFox\|wheningit\|git-animals\|artlebedev\|shpengler-v\|this-plt-life\|morekoda\|pbfcomics\|gsfc[.]nasa'
COFFEE_FILTER='fmylife\|bash[.]im\|zadolba[.]li\|perashki\|killmepls\|ibash\|korrespondent\|ithappens'
TOREAD_FILTER='habrahabr\|thedailywtf\|xkcd[.]com\|ct_news\|elementy\|ttolk\|smartfiction\|useless-faq\|metallibrary\|instead[.]syscall\|gutta-honey\|tumbalele\|venena-letalis\|linux[.]org[.]ru\|factroom\|dou[.]ua\|lurkmore\|roguetemple\|dzone\|toster[.]ru'
COMPULENTA_FILTER='compulenta'
ATO_FILTER='korrespondent'
if [ -d "$GOOD_DIR" ]; then
	pushd "$GOOD_DIR" >/dev/null
	for f in *; do
		[ -d "$f" ] && continue
		cat -- "$f" | grep -q "$ATO_FILTER" && mkdir -p "$ATO_DIR" && mv -v -- "$f" "$ATO_DIR" && continue
		cat -- "$f" | grep -q "$COMIC_FILTER" && mkdir -p "$COMIC_DIR" && mv -v -- "$f" "$COMIC_DIR" && continue
		cat -- "$f" | grep -q "$COFFEE_FILTER" && mkdir -p "$COFFEE_DIR" && mv -v -- "$f" "$COFFEE_DIR" && continue
		cat -- "$f" | grep -q "$TOREAD_FILTER" && mkdir -p "$TOREAD_DIR" && mv -v -- "$f" "$TOREAD_DIR" && continue
		cat -- "$f" | grep -q "$COMPULENTA_FILTER" && mkdir -p "$COMPULENTA_DIR" && mv -v -- "$f" "$COMPULENTA_DIR"/"$(echo $f | sed 's/?/_/g')" && continue
	done
	popd >/dev/null
fi

rmdir "$ROOT_DIR"/* 2>/dev/null

shopt -u dotglob
